name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Prepare environment
        uses: ./.github/actions/prepare

      - name: Run Build
        run: pnpm build
        env:
          POSTGRES_URL: postgresql://dummy:dummy@localhost:5432/dummy
